### ISSUE TITLE
Add Automated Documentation to Rakefile

### ISSUE THREAD

**Issue by LeftoverCurry** [ChaelCodes/HuntersKeepers#132]
## Description
**Enable Automated Documentation**
The Annotate gem allows us to have automatic documentation of model-related files and specs whenever a new migration is run, but comes out-of-the-box with the option disabled. 

## Implementation of the Solution
**Add Task to Rakefile**
* Navigate to `~/HuntersKeepers/Rakefile`

Add line to file, as shown in the documentation:
![Screen Shot 2020-06-01 at 11 02 51 AM](https://user-images.githubusercontent.com/20918543/83431179-ec546600-a404-11ea-954f-360db31e7eae.png)

**References**
[Annotate Documentation](https://github.com/ctran/annotate_models)

**Comment by jash-kothari** [comment]
Picking this issue up.
