### ISSUE TITLE
Add User Authentication

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HuntersKeepers#17]
This first issue is just for adding Devise and users, then we'll start talking permissions.
1. Add Devise
   - Follow the [Rails Girls guide for adding Devise](https://guides.railsgirls.com/devise)
   - Skip anything referencing "Idea"
1. Add [Pundit using the steps in their README](https://github.com/varvet/pundit)
1. Create a migration to add a `user_id:integer` column to hunters
1. Update `hunters_controller` to populate `user_id` with current user
1. Create a HunterPolicy that only allows the User to update/destroy their hunter
1. Create a migration to add an `admin:boolean` column to users
1. Update HunterPolicy to allow admins to update/destroy Hunters too.

**Comment by OldRice42** [comment]
We need to add a way for the user to go back to the page they were on when they logged in. We also need to redirect the user to the Welcome page when they have logged out.

**Comment by ChaelCodes** [comment]
Here's some documentation on redirecting from devise: https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-on-successful-sign-in
