### ISSUE TITLE
Implement validation when adding/editing Moves

### ISSUE THREAD

**Issue by bipster** [ChaelCodes/HuntersKeepers#170]
**Describe the bug**
There is currently no validation for Moves.  You can create Moves by submitting the blank form, or blank-out names of existing Moves.  The "Name:" field, at the very least, should probably be required.

**To Reproduce**
1. Go to `/moves/new`
2. Click "Create Move"

**Expected behavior**
An error precluding the Move creation due to -- at the very least -- a missing name.

**Screenshots**
<img width="150" alt="CleanShot 2020-09-12 at 18 17 24@2x" src="https://user-images.githubusercontent.com/796596/93005957-9d01f380-f524-11ea-84bc-71958acfd828.png">

**Comment by ChaelCodes** [comment]
We need to ensure there is a name and a description, everything else should be optional.

**Comment by JuanVqz** [comment]
I want to contribute here, Can you assing me, please?
