### ISSUE TITLE
Establish dependent relationships to Destroy Hunters

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HuntersKeepers#172]
**Describe the bug**
Users cannot destroy Hunters, because hunters_moves are not destroyed when hunters are.

**To Reproduce**
1. While logged in,
1. Create a hunter
1. Edit the Hunter
1. Check a Move
1. Submit in the moves column
1. Go back to `/hunters`
1. Click destroy on that hunter

**Expected behavior**
Hunter is deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/8124558/93020273-07a94280-f5aa-11ea-94f2-7ebce158af05.png)

** Solution**
Define dependent relationships on [hunter model](https://github.com/ChaelCodes/HuntersKeepers/blob/master/app/models/hunter.rb) for hunter moves

**Comment by ChaelCodes** [comment]
The issue reproduction steps may be blocked by #161

**Comment by jash-kothari** [comment]
Picking this up.
