### ISSUE TITLE
Exclude json.jbuilder files from magic comment rubocop check

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HuntersKeepers#202]
## Describe the Feature
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/8124558/103481034-2d02cc00-4da6-11eb-8ead-04bf98846a1a.png)
RuboCop reports on missing magic comments for jbuilder templates, but jbuilder doesn't even use magic comments.

**Additional context**

## Describe the Technical Implementation of the Solution
**Solution**
Exclude files with a jbuilder.json file extension from the magic comment rule, and remove magic comments.

**References**
Any references to materials or help articles that may help in implementing this issue.

**Comment by muydanny** [comment]
I'd like to work on this issue 👨🏽‍💻
