### ISSUE TITLE
Allow admins to delete playbooks

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HuntersKeepers#213]
**Describe the bug**
Right now Admins cannot delete playbooks due to foreign key constraints on Moves, Improvements, and Gear. There's also Ratings, but these don't block deletion, because Hunters copy instead of referencing ratings. This is a bit more complicated, because Hunters reference these values. What should happen to the Hunter, when the playbook is removed?

**To Reproduce**
1. Login as Admin
1. Go to '/playbooks'
1. Click on 'Destroy'
1. Confirm destroy in dialog. 

**Expected behavior**
The playbook is destroyed.

What happens to the hunter?

**Screenshots**

**Additional context**
Also, Playbooks report they are successfully deleted when they are not.

**Comment by JuanVqz** [comment]
We can use an alternative instead of delete the record.

https://github.com/jhawthorn/discard

https://github.com/grosser/soft_deletion

**Comment by LittleBigProgramming** [comment]
This is a really good alternative for soft deletes https://github.com/ActsAsParanoid/acts_as_paranoid 🙂

**Comment by muydanny** [comment]
- Add column ArchivedAt

- In the controller call new archive method - use instead of delete or destroy

- Can replace destroy with new method 

- Method Archive and leave destroy so we don't have a DESTROY DESTROY (Dont need exterminate 😈)
