### ISSUE TITLE
Allow Users to View, but not Create, Edit, nor Destroy without Authentication

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HuntersKeepers#69]
**Describe the bug**
We want to let people view the application if they're not logged in, but they shouldn't be able to wreak havoc without giving me an email, so I can write them a scathing email.

**To Reproduce**
- While not logged in
- Go to 'http://hunters-keepers.herokuapp.com/hunters
- [ ] Expected: You should be able to view Hunters that other have created
- Actual: You are redirected to sign in
- Attempt to Create a Hunter
- [ ] Expected + Actual: You are redirected to sign in

**Additional context**
We're using Devise to authenticate users on the ApplicationController, and we've created a new HunterPolicy using pundit. One, or both of these, is being too aggressive in authentication + authorization. I think it's devise.
https://github.com/ChaelCodes/HuntersKeepers/blob/2233a1b9e1f6346766835bf643227227226215a4/app/controllers/application_controller.rb#L8
^ This probably needs to be shoved into the inheriting controllers, but take a look, see what you can find out.

**Comment by ChaelCodes** [comment]
@LeftoverCurry take a look at this one, and let me know what you think.

**Comment by LeftoverCurry** [comment]
I'll look it over and see what I can do.
