### ISSUE TITLE
Make a Rad Flavicon for HuntersKeepers

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HuntersKeepers#71]
## Describe the Feature
I want to see a little icon in my chrome tab, so I can jump straight to HuntersKeepers!

## Describe the Technical Implementation of the Solution
**Solution**
- [ ] Design HuntersKeepers Logo
- [ ] Add the image to the assets folder
- [ ] Add the favicon helper to application.html.erb

**References**
Check out this Issue where it was done on Pixie: https://github.com/ChaelCodes/strawberry-machine-cake/issues/10

**Comment by ChaelCodes** [comment]
Designers, you can win Hacktoberfest too!

**Comment by JuanVqz** [comment]
Would I grab this issue, please?
