### ISSUE TITLE
Create Character Class

### ISSUE THREAD

**Issue by OldRice42** [ChaelCodes/HuntersKeepers#8]
# Description
Create a character class where users store their character information. This includes Character Name, Ratings, Harm, Luck and Experience.
# Solution
1 Table, Scaffold command

|  Column Name | Data Type  |
|  ------------- | -------------  |
|  name | string  |
|  harm | integer   |
|  luck | integer  |
|  experience | integer  |
|  charm | integer  |
|  cool | integer  |
|  sharp | integer  |
|  tough | integer  |
|  weird | integer  |

`rails generate scaffold Character name:string harm:integer luck:integer experience:integer charm:integer cool:integer sharp:integer tough:integer weird:integer`

**Comment by ChaelCodes** [comment]
We should probably rename this Hunter.
